### ISSUE TITLE
No Trellis project detected in the current directory or any of its parent directories.

### ISSUE THREAD

**Issue by spetrey** [ItinerisLtd/tiller-circleci-orb#23]
**Orb Version**
3.4.0

**Describe the bug**
CI fails at prepare_trellis step:
```
#!/bin/bash -eo pipefail
trellis init
No Trellis project detected in the current directory or any of its parent directories.

Exited with code exit status 1
CircleCI received exit code 1
```

**To Reproduce**
Here's my example config.yml:
```
version: 2.1

orbs:
  tiller-circleci: itinerisltd/tiller-circleci@3.4.0
  cypress: cypress-io/cypress@1

executors:
  php-74:
    docker:
      - image: circleci/php:7.4-stretch
  node-12:
    docker:
      - image: itinerisltd/tiller-circleci:node-12

workflows:
  deploy:
    jobs:
      - tiller-circleci/deploy:
          name: deploy-production
          known-hosts: 'github.com, 140.82.114.3, 140.82.112.4, 140.82.114.4, 140.82.112.3' # GitHub.com hosts and IPs
          trellis-branch: main # or master if you prefer
          trellis-repo: git@github.com:roots/roots-example-project.git
          site-env: production
          site-name: example.com
          executor-tag: node-12
          vault-password: VAULT_PASSWORD

```

**Expected behavior**

This should work...I think. But I can't find an example config.yml for 3.4.0, so I'm flying blind here. Maybe I'm missing something. I'm using the expected and opinionated trellis & bedrock directory structure as seen here:
https://github.com/roots/roots-example-project.com

**Additional context**
This issue has something to do with this: https://github.com/ItinerisLtd/tiller-circleci-orb/pull/22
Given that the error happens when the CI runs `trellis init`.
