### ISSUE TITLE
Data could not be sent to remote host

### ISSUE THREAD

**Issue by stefthoen** [ItinerisLtd/tiller-circleci-orb#24]
I'm afraid this might be more of a support question and not a bug, but I'd appreciate it if you could point me into the right direction anyway. I've used this Orb the last couple of years on and off again, but when I try to use it in a new project I'm getting stuck at the following step:

`trellis exec ansible-playbook deploy.yml -vvv -e env=staging -e site=my-site.com` 

CircleCI mentions the following: 

```Data could not be sent to remote host "IP NUMBER". Make sure this host can be reached over ssh: web@IP NUMBER: Permission denied (publickey).```

I can access my DO droplet locally as `web`. Although I've used this Orb in earlier projects, I'm not clear how CircleCI's project keys should be configured. I have a **Deploy Key** and a **User Key**, but I'm not sure if the latter is necessary.

The following is my `config.yml`:
```
version: 2.1

orbs:
  tiller-circleci: itinerisltd/tiller-circleci@3.4.0
  
workflows:
  deploy:
    jobs:
      - tiller-circleci/deploy:
          name: deploy-staging
          known-hosts: 'github.com, IP NUMBER'
          trellis-repo: 'git@github.com:stefthoen/my-site.com-trellis.git'
          site-env: staging
          site-name: my-site.com
          filters:
            branches:
              only: master
```
My `group_vars/all/users.yml` is configured as such:
```
# Documentation: https://roots.io/trellis/docs/ssh-keys/
admin_user: admin

# Also define 'vault_users' (`group_vars/staging/vault.yml`, `group_vars/production/vault.yml`)
users:
  - name: "{{ web_user }}"
    groups:
      - "{{ web_group }}"
    keys:
      - https://github.com/stefthoen.keys
  - name: "{{ admin_user }}"
    groups:
      - sudo
    keys:
      - https://github.com/stefthoen.keys

web_user: web
web_group: www-data
web_sudoers:
  - "/usr/sbin/service php{{ php_version }}-fpm *"
```
Do you have any idea what I could be doing wrong @TangRufus? What is the correct way to configure SSH keys in CircleCI so it works correctly with this orb? Thanks!
