### ISSUE TITLE
tiller-circleci: Support the Roots.io offical file structure

### ISSUE THREAD

**Issue by tjedrak** [ItinerisLtd/tiller-circleci-orb#6]
I tried your Orb config v0.7.0. Can't get it to work. It's probably with vault_password variable - which I have in CircleCI.

![Screenshot 2020-02-26 at 19 14 11](https://user-images.githubusercontent.com/5551518/75374361-7227b900-58cc-11ea-8114-8bf0d9385350.jpg)

Any idea what I did wrong?

Also my config below:
```
version: 2.1
orbs:
  tiller-circleci: itinerisltd/tiller-circleci@0.7.0
deploy-config:
  known_hosts: "github.com, staging.kryptokasyna.com, new.kryptokasyna.com"
  trellis_repo: "git@bitbucket.org:one7six/kryptokasyna.git"
  vault_password: "vault_password"
  vault_password_file: ".vault_pass"
critical_urls: "https://staging.kryptokasyna.com https://staging.kryptokasyna.com/wp-json"

workflows:
  deploy:
    jobs:
      - tiller-circleci/deploy:
          name: deploy-staging
          known_hosts: "bitbucket.org, github.com, staging.kryptokasyna.com"
          trellis_repo: "git@bitbucket.org:one7six/kryptokasyna.git"
          site_name: staging.kryptokasyna.com
          site_env: staging
          filters:
            branches:
              only: develop
  deploy-production-with-manual-approval:
    jobs:
      - hold:
          type: approval
          filters:
            branches:
              only: master
      - tiller-circleci/deploy:
          known_hosts: "bitbucket.org, github.com, new.kryptokasyna.com"
          trellis_repo: "git@bitbucket.org:one7six/kryptokasyna.git"
          site_name: new.kryptokasyna.com
          site_env: production
          requires:
            - hold
          filters:
            branches:
              only: master
```

Got these errors:

![Screenshot 2020-02-26 at 19 17 22](https://user-images.githubusercontent.com/5551518/75374480-a9966580-58cc-11ea-9cac-e463d4363425.jpg)

```
error computing cache key: template: cacheKey:1:55: executing "cacheKey" at <checksum "trellis/galaxy.yml">: error calling checksum: open /home/circleci/project/trellis/galaxy.yml: no such file or directory
```

```
#!/bin/bash -eo pipefail
trellis deploy staging staging.kryptokasyna.com

Running command => ansible-playbook deploy.yml -e env=staging site=staging.kryptokasyna.com
ERROR! The vault password file /home/circleci/project/trellis/trellis/.vault_pass was not found
2020/02/26 18:07:52 exit status 1

Exited with code exit status 1
CircleCI received exit code 1
```
